name: YouTube Livestream Transcript Extractor

on:
  schedule:
    # 毎時0分に実行
    - cron: '0 * * * *'
  workflow_dispatch:  # 手動実行用

jobs:
  extract-transcript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: paji/82ch
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create target directory
        run: mkdir -p youtube_text

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Run transcript extractor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python youtube_livestream_extractor.py

      - name: Setup Git for target repository
        run: |
          cd youtube_text
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/paji/youtube_text.git
          # リポジトリが空の場合に備えて空のコミットを作成
          git commit --allow-empty -m "Initial commit"
          # 強制的にプッシュ（リポジトリが存在しない場合は失敗するが、存在する場合は成功する）
          git push --set-upstream origin main || echo "Repository may not exist yet"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          cd youtube_text
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Add new transcript via GitHub Actions"
          git push --set-upstream origin main || git push --set-upstream origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
