name: YouTube過去配信取得

on:
  schedule:
    # 毎日午前3時に実行（UTC）
    - cron: '0 3 * * *'
  workflow_dispatch:
    # 手動実行用

# リポジトリへの書き込み権限を付与
permissions:
  contents: write

jobs:
  extract_livestreams:
    runs-on: ubuntu-latest
    
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      
      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib requests
      
      - name: 過去配信一覧の取得
        run: |
          # ファイルの存在を確認
          ls -la
          # 正しいファイル名で実行し、直接チャンネルIDを指定
          python youtube_livestream_extractor.py --channel-id UCYQ1MkR00l647L23RpJM-8g --output livestreams.json
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      
      - name: 変更をコミット
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add livestreams.json
          git diff --quiet && git diff --staged --quiet || git commit -m "過去配信一覧を更新 $(date '+%Y-%m-%d')"
      
      - name: 変更をプッシュ
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
