name: YouTube Livestream Transcript Extractor

on:
  schedule:
    # 毎時0分に実行
    - cron: '0 * * * *'
  workflow_dispatch:  # 手動実行用

jobs:
  extract-transcript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: paji/82ch
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create target directory
        run: mkdir -p youtube_text

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Run transcript extractor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python youtube_livestream_extractor.py

      - name: Save transcripts locally
        run: |
          # 文字起こしファイルをローカルに保存
          mkdir -p transcripts
          if [ -d "youtube_text" ]; then
            cp -r youtube_text/* transcripts/ 2>/dev/null || true
          fi

      - name: Upload transcripts as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: transcripts
          path: transcripts/
          retention-days: 7
