name: YouTube動画文字起こし

on:
  schedule:
    # 1時間ごとに実行
    - cron: '0 * * * *'
  workflow_dispatch:
    # 手動実行用

# リポジトリへの書き込み権限を付与
permissions:
  contents: write

jobs:
  transcribe_video:
    runs-on: ubuntu-latest
    
    steps:
      - name: 82chリポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          repository: paji/82ch
          token: ${{ secrets.PAT_TOKEN }}
          path: 82ch
      
      - name: youtube_textリポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          repository: paji/youtube_text
          token: ${{ secrets.PAT_TOKEN }}
          path: youtube_text
      
      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib requests youtube-transcript-api
      
      - name: 文字起こしスクリプトの実行
        run: |
          python 82ch/youtube_transcription.py \
            --livestreams-json 82ch/livestreams.json \
            --output-dir youtube_text
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      
      - name: 変更の確認（youtube_text）
        id: check_changes
        run: |
          cd youtube_text
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: 変更をコミット（youtube_text）
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cd youtube_text
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "文字起こしを追加 $(date '+%Y-%m-%d %H:%M')"
      
      - name: 変更をプッシュ（youtube_text）
        if: steps.check_changes.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          directory: youtube_text
          repository: paji/youtube_text
