name: YouTube Livestream Transcript Extractor

on:
  schedule:
    # 毎時0分に実行
    - cron: '0 * * * *'
  workflow_dispatch:  # 手動実行用

jobs:
  extract-transcript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout youtube_text repository
        uses: actions/checkout@v3
        with:
          repository: paji/youtube_text
          token: ${{ secrets.GITHUB_TOKEN }}
          path: youtube_text

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Fetch extractor script
        uses: actions/checkout@v3
        with:
          repository: paji/82ch
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 82ch
          sparse-checkout: |
            youtube_livestream_extractor.py
            livestreams.json

      - name: Run transcript extractor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          cd 82ch
          python youtube_livestream_extractor.py

      - name: Commit changes if any
        run: |
          cd youtube_text
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Add new transcript via GitHub Actions"
          git push
